### ISSUE TITLE
Doesn't work for short sequence and .ent doesn't work

### ISSUE THREAD

**Issue by HuangHam** [sztal/pybdm#18] opened 2024-02-10 02:55 UTC
Hi! I am trying to get a algorithmic complexity measure for length 10 binary sequences. But bdm = BDM(ndim=1) bdm.bdm(X) raised valuewarning that every length 10 binary sequences is 0. Also bdm.ent always yield 0 while it's impossible the shannon entropy of all sequence is zero.

**Comment by sztal** [comment] 2024-02-10 14:19
Hi, by default `BDM` class with `ndim=1` uses a default block shape of `(12,)` and partition boundary rule ignoring leftover blocks smaller than the expected shape.

To get complexity estimates for smaller blocks / shorter strings you can do one of two things, depending on your usecase.

## Option 1

This is a good solution if you know that all string you will analyze will have the same lengths, e.g. 10.

```python
from pybdm import BDM
import numpy as np

seq  = np.ones(10, dtype=int)
bdm = BDM(ndim=1, shape=(10,))
bdm.bdm(seq)
# OUTPUT: 22.784225562763474
```

## Option 2

When you may have to work with strings of various sizes and you do not want to lose results for short strings.

```python
from pybdm import BDM, PartitionRecursive
bdm = BDM(ndim=1, partition=PartitionRecursive)
seq = np.ones(10, dtype=int)

bdm.bdm(seq)
# OUTPUT: 22.784225562763474
```

In this case we specified so-called recursive partition boundary condition, which means that left overs smaller than the expected block shape (which is by default set to `(12,)` for 1D problems) are not discarded.

I hope this helps.

**Comment by HuangHam** [comment] 2024-02-12 01:39
Thank you very much! Option1 is exactly what I am doing and it works! I also noticed that this package gives the same output as the R package https://www.rdocumentation.org/packages/acss/versions/0.2-5/topics/acss Are these two packages using the same algorithm?

**Comment by sztal** [comment] 2024-02-12 11:43
You're welcome! And regarding the ACSS package, it implements the Coding Theorem Method , aka CTM (described here: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0096223), which is applicable only to short strings (e.g. not longer than elements).

On the other hand, `pybdm` implements Block Decomposition Method, aka BDM (described here: https://www.mdpi.com/1099-4300/20/8/605), which is a generalization of CTM that can be applied to strings of arbitrary lengths. Crucially, the two methods produce the same results for short strings.

I am closing this issue now, since the problem is solved.

**Closed by sztal** 2024-02-12 11:43 UTC
